export const START_API_REQUEST = 'START_API_REQUEST';
export const FINISH_API_REQUEST = 'FINISH_API_REQUEST';
export const ERROR_API_REQUEST = 'ERROR_API_REQUEST';
export const LOAD_BOOKS = 'LOAD_BOOKS';
export const RECEIVE_BOOKS = 'RECEIVE_BOOKS';
export const REQUEST_ADD_BOOK = 'REQUEST_ADD_BOOK';
export const ADD_BOOK = 'ADD_BOOK';
export const REQUEST_DELETE_BOOK = 'REQUEST_DELETE_BOOK';
export const DELETE_BOOK = 'DELETE_BOOK';
export const REQUEST_UPDATE_BOOK = 'REQUEST_UPDATE_BOOK';
export const UPDATE_BOOK = 'UPDATE_BOOK';
export const CHANGE_ADD_FORM_VALUE = 'CHANGE_ADD_FORM_VALUE';
export const RESET_ADD_FORM = 'RESET_ADD_FORM';
export const CHANGE_SEARCH_FORM_VALUE = 'CHANGE_SEARCH_FORM_VALUE';
export const CHANGE_BOOK_CONTROL_FORM_VALUE = 'CHANGE_BOOK_CONTROL_FORM_VALUE';
export const CHANGE_BOOK_CONTROL_FORM_EDIT_MODE =
  'CHANGE_BOOK_CONTROL_FORM_EDIT_MODE';
export const VALIDATE_BOOK_CONTROL_FORM = 'VALIDATE_BOOK_CONTROL_FORM';
