export const ADD_BOOK = 'ADD_BOOK';
export const DELETE_BOOK = 'DELETE_BOOK';
export const CHANGE_ADD_FORM_VALUE = 'CHANGE_ADD_FORM_VALUE';
export const CHANGE_SEARCH_FORM_VALUE = 'CHANGE_SEARCH_FORM_VALUE';
